
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
      ignoredNodes:
        - TemplateLiteral *
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: always-multiline
overrides:
  - files:
    - '**/__test__/*.spec.ts'
